import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle } from "lucide-react";

const disclaimerContent = {
  en: {
    title: "Disclaimer",
    effectiveDate: "Effective Date: May 13, 2026",
    lastUpdated: "Last Updated: May 13, 2026",
    sections: [
      {
        title: "1. No Investment Advice",
        content: `Nothing on the PECT Platform (pect-dapp.io) constitutes financial, investment, legal, tax, or any other professional advice. All information provided on the Platform is for informational and educational purposes only. You should consult with qualified professional advisors before making any investment decisions. PECT DApp is not a registered investment advisor, broker-dealer, or financial institution in any jurisdiction.`,
      },
      {
        title: "2. No Guarantee of Returns",
        content: `Participation in the PECT ecosystem, including purchasing PV-Coin (PVC), staking C2-Coin (C2C), or receiving revenue distributions, involves significant financial risk. All projected returns, estimated yields, and historical performance data presented on the Platform are illustrative only and do not constitute a guarantee, promise, or representation of future results. Actual returns may be materially lower than projected, and you may lose some or all of your invested capital.

The revenue generated by photovoltaic energy stations is subject to numerous variables, including but not limited to: weather conditions, equipment performance and degradation, grid connectivity and curtailment, electricity pricing and regulatory changes, operational costs, and force majeure events. None of these factors are within the full control of PECT DApp.`,
      },
      {
        title: "3. Regulatory and Legal Risk",
        content: `The regulatory status of blockchain-based tokens, digital assets, and decentralized finance (DeFi) protocols is uncertain and evolving across jurisdictions worldwide. It is your sole responsibility to determine whether your participation in the PECT ecosystem is lawful in your jurisdiction. PECT DApp makes no representation that the Platform, PVC, or C2C complies with the laws of any particular jurisdiction.

Regulatory changes, including the classification of PVC or C2C as securities, the imposition of licensing requirements, or outright prohibition of digital asset activities, could materially and adversely affect the value of your holdings and your ability to use the Platform.`,
      },
      {
        title: "4. Technology and Smart Contract Risk",
        content: `Blockchain technology, smart contracts, and decentralized applications involve inherent technological risks, including but not limited to:

• **Smart Contract Vulnerabilities:** Despite security audits, smart contracts may contain undiscovered bugs, logic errors, or vulnerabilities that could be exploited by malicious actors, resulting in partial or total loss of digital assets.
• **Blockchain Network Risk:** The Polygon network and its underlying infrastructure may experience congestion, forks, attacks, or other disruptions that could delay or prevent transactions.
• **Wallet and Key Management Risk:** Loss, theft, or compromise of your private keys or seed phrases will result in permanent and irrecoverable loss of your digital assets. PECT DApp has no ability to recover lost keys or reverse unauthorized transactions.
• **Oracle Risk:** Revenue distribution calculations rely on external data feeds (oracles) that report electricity generation and pricing data. Oracle failures, manipulation, or inaccuracies could affect distribution amounts.
• **Protocol Upgrades:** Smart contract protocols may require upgrades that could affect functionality or require user action.`,
      },
      {
        title: "5. Market and Liquidity Risk",
        content: `PVC and C2C tokens may be subject to extreme price volatility. The market value of these tokens may fluctuate significantly and may decrease to zero. There is no guarantee that a liquid secondary market will exist for PVC or C2C at any time. You may be unable to sell or transfer your tokens at a price acceptable to you, or at all.`,
      },
      {
        title: "6. Operational Risk",
        content: `PECT DApp's photovoltaic energy stations are physical assets subject to operational risks including equipment failure, natural disasters, fire, theft, regulatory shutdowns, grid disconnection, and other events that may reduce or eliminate electricity generation and associated revenue. Insurance coverage, if any, may not fully compensate for all losses.`,
      },
      {
        title: "7. Third-Party Services",
        content: `The Platform integrates with third-party services including blockchain networks, wallet providers, data oracles, and identity verification services. PECT DApp is not responsible for the performance, availability, security, or accuracy of any third-party service. Your use of third-party services is subject to their respective terms and conditions.`,
      },
      {
        title: "8. Forward-Looking Statements",
        content: `Certain statements on the Platform may constitute forward-looking statements, including projections of revenue, token issuance schedules, and development roadmaps. These statements are based on current expectations and assumptions and are subject to significant risks and uncertainties. Actual results may differ materially from those expressed or implied in any forward-looking statement. PECT DApp undertakes no obligation to update forward-looking statements to reflect subsequent events or circumstances.`,
      },
      {
        title: "9. Exclusion of Liability",
        content: `TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, PECT DAPP, ITS FOUNDERS, OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AND AGENTS EXPRESSLY DISCLAIM ALL LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES ARISING FROM OR RELATED TO:

• Your use of or inability to use the Platform;
• Any loss or theft of digital assets;
• Smart contract failures, bugs, or exploits;
• Regulatory actions affecting the Platform or your holdings;
• Market price fluctuations of PVC or C2C;
• Inaccuracies in oracle data or revenue calculations;
• Third-party service failures;
• Force majeure events affecting photovoltaic station operations.`,
      },
      {
        title: "10. Jurisdictional Restrictions",
        content: `The Platform is not intended for use by citizens or residents of jurisdictions where participation in blockchain-based token offerings is prohibited or restricted by law. By using the Platform, you represent that you are not located in, or a citizen or resident of, any such restricted jurisdiction. It is your responsibility to ensure compliance with all applicable local laws.`,
      },
      {
        title: "11. No Warranty",
        content: `THE PLATFORM IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR UNINTERRUPTED OR ERROR-FREE OPERATION. PECT DAPP DOES NOT WARRANT THAT THE PLATFORM WILL MEET YOUR REQUIREMENTS OR THAT ANY ERRORS WILL BE CORRECTED.`,
      },
      {
        title: "12. Acknowledgment of Risk",
        content: `By using the Platform, you expressly acknowledge that you have read, understood, and accepted all risks described in this Disclaimer, our Terms of Service, and Privacy Policy. You confirm that you are participating in the PECT ecosystem of your own free will, with full knowledge of the risks involved, and that you are financially and technically capable of bearing such risks.`,
      },
      {
        title: "13. Contact Us",
        content: `For questions regarding this Disclaimer, please contact us:\n\nEmail: contact@pect-dapp.io\nTelegram: t.me/PECT_OFCL\nDiscord: discord.gg/6DGzsQpw4`,
      },
    ],
  },
  zh: {
    title: "免责声明",
    effectiveDate: "生效日期：2026 年 5 月 13 日",
    lastUpdated: "最后更新：2026 年 5 月 13 日",
    sections: [
      {
        title: "1. 非投资建议",
        content: `PECT 平台（pect-dapp.io）上的任何内容均不构成财务、投资、法律、税务或任何其他专业建议。平台提供的所有信息仅供参考和教育目的。在作出任何投资决策之前，您应咨询合格的专业顾问。PECT DApp 在任何司法管辖区均未注册为投资顾问、经纪商或金融机构。`,
      },
      {
        title: "2. 不保证收益",
        content: `参与 PECT 生态系统，包括购买 PV-Coin（PVC）、质押 C2-Coin（C2C）或获取收益分配，涉及重大财务风险。平台上呈现的所有预测收益、估算收益率和历史业绩数据仅供说明，不构成对未来结果的保证、承诺或陈述。实际收益可能远低于预测，您可能损失部分或全部投入资本。

光伏能源电站产生的收益受众多变量影响，包括但不限于：天气状况、设备性能及老化、电网连接及弃电、电价及监管变化、运营成本及不可抗力事件。上述因素均非 PECT DApp 能完全控制。`,
      },
      {
        title: "3. 监管与法律风险",
        content: `基于区块链的代币、数字资产及去中心化金融（DeFi）协议的监管状态在全球各司法管辖区仍不确定且持续演变。判断您参与 PECT 生态系统是否在您所在司法管辖区合法，完全是您的责任。PECT DApp 不对平台、PVC 或 C2C 符合任何特定司法管辖区的法律作出任何陈述。

监管变化，包括将 PVC 或 C2C 认定为证券、施加许可要求或全面禁止数字资产活动，可能对您的持仓价值及使用平台的能力产生重大不利影响。`,
      },
      {
        title: "4. 技术与智能合约风险",
        content: `区块链技术、智能合约和去中心化应用涉及固有的技术风险，包括但不限于：

• **智能合约漏洞：** 尽管经过安全审计，智能合约可能包含未被发现的漏洞、逻辑错误，可能被恶意行为者利用，导致数字资产部分或全部损失。
• **区块链网络风险：** Polygon 网络及其底层基础设施可能出现拥堵、分叉、攻击或其他中断，可能延迟或阻止交易。
• **钱包与密钥管理风险：** 私钥或助记词的丢失、被盗或泄露将导致数字资产永久且不可恢复的损失。PECT DApp 无法恢复丢失的密钥或撤销未经授权的交易。
• **预言机风险：** 收益分配计算依赖报告发电量和电价数据的外部数据源（预言机）。预言机故障、操纵或数据不准确可能影响分配金额。
• **协议升级：** 智能合约协议可能需要升级，这可能影响功能或需要用户采取行动。`,
      },
      {
        title: "5. 市场与流动性风险",
        content: `PVC 和 C2C 代币可能面临极端价格波动。这些代币的市场价值可能大幅波动，并可能降至零。不保证 PVC 或 C2C 在任何时候存在流动性二级市场。您可能无法以您可接受的价格出售或转让代币，甚至无法出售或转让。`,
      },
      {
        title: "6. 运营风险",
        content: `PECT DApp 的光伏能源电站是实物资产，面临运营风险，包括设备故障、自然灾害、火灾、盗窃、监管关停、电网断开及其他可能减少或消除发电量及相关收益的事件。保险（如有）可能无法完全补偿所有损失。`,
      },
      {
        title: "7. 第三方服务",
        content: `平台与第三方服务集成，包括区块链网络、钱包提供商、数据预言机及身份核实服务。PECT DApp 对任何第三方服务的性能、可用性、安全性或准确性不承担责任。您对第三方服务的使用受其各自条款和条件约束。`,
      },
      {
        title: "8. 前瞻性陈述",
        content: `平台上的某些陈述可能构成前瞻性陈述，包括收益预测、代币发行计划和发展路线图。这些陈述基于当前预期和假设，面临重大风险和不确定性。实际结果可能与任何前瞻性陈述中明示或暗示的结果存在重大差异。PECT DApp 不承担更新前瞻性陈述以反映后续事件或情况的义务。`,
      },
      {
        title: "9. 责任排除",
        content: `在适用法律允许的最大范围内，PECT DAPP 及其创始人、高管、董事、员工、承包商和代理人明确声明对以下原因产生或与之相关的任何直接、间接、附带、特殊、后果性或惩戒性损害不承担任何责任：

• 您使用或无法使用平台；
• 数字资产的任何损失或被盗；
• 智能合约故障、漏洞或被利用；
• 影响平台或您持仓的监管行动；
• PVC 或 C2C 的市场价格波动；
• 预言机数据或收益计算不准确；
• 第三方服务故障；
• 影响光伏电站运营的不可抗力事件。`,
      },
      {
        title: "10. 司法管辖区限制",
        content: `平台不面向法律禁止或限制参与基于区块链代币发行的司法管辖区的公民或居民。使用平台即表示您声明您不位于任何此类受限司法管辖区，也不是其公民或居民。确保遵守所有适用当地法律是您的责任。`,
      },
      {
        title: "11. 无保证",
        content: `平台按"现状"和"可用"基础提供，不附带任何形式的明示或暗示保证，包括但不限于适销性、特定用途适用性、不侵权或不间断或无错误运行的保证。PECT DAPP 不保证平台将满足您的要求或任何错误将被纠正。`,
      },
      {
        title: "12. 风险确认",
        content: `使用平台即表示您明确承认您已阅读、理解并接受本免责声明、服务条款和隐私政策中描述的所有风险。您确认您是出于自由意志参与 PECT 生态系统，充分了解所涉及的风险，并在财务和技术上有能力承担此类风险。`,
      },
      {
        title: "13. 联系我们",
        content: `如对本免责声明有任何疑问，请联系我们：\n\n电子邮件：contact@pect-dapp.io\nTelegram：t.me/PECT_OFCL\nDiscord：discord.gg/6DGzsQpw4`,
      },
    ],
  },
};

export default function Disclaimer() {
  const [lang, setLang] = useState<"en" | "zh">("zh");
  const content = disclaimerContent[lang];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 py-10">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center">
              <AlertTriangle className="w-5 h-5 text-amber-600" />
            </div>
            <Badge variant="outline" className="text-amber-700 border-amber-300 bg-amber-50">
              Legal Document
            </Badge>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">{content.title}</h1>
          <p className="text-sm text-gray-500">{content.effectiveDate} &nbsp;·&nbsp; {content.lastUpdated}</p>
          <div className="flex gap-2 mt-4">
            <Button
              variant={lang === "zh" ? "default" : "outline"}
              size="sm"
              onClick={() => setLang("zh")}
            >
              中文
            </Button>
            <Button
              variant={lang === "en" ? "default" : "outline"}
              size="sm"
              onClick={() => setLang("en")}
            >
              English
            </Button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-10">
        {/* Warning Banner */}
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-6 flex gap-3">
          <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-amber-800">
            {lang === "zh"
              ? "重要提示：参与 PECT 生态系统涉及重大财务风险，包括可能损失全部投入资本。请在参与前仔细阅读本免责声明的全部内容。"
              : "Important: Participation in the PECT ecosystem involves significant financial risk, including the possible loss of all invested capital. Please read this Disclaimer in its entirety before participating."}
          </p>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
          <div className="divide-y divide-gray-100">
            {content.sections.map((section, idx) => (
              <div key={idx} className="px-8 py-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-3">{section.title}</h2>
                <div className="text-gray-600 text-sm leading-relaxed whitespace-pre-line">
                  {section.content.split("**").map((part, i) =>
                    i % 2 === 1 ? (
                      <strong key={i} className="text-gray-800 font-semibold">
                        {part}
                      </strong>
                    ) : (
                      <span key={i}>{part}</span>
                    )
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

        <p className="text-center text-xs text-gray-400 mt-8">
          © 2026 PECT DApp. All rights reserved.
        </p>
      </div>
    </div>
  );
}
