// Vercel Serverless Function entry point
// This file re-exports the Express app from the built dist/index.js
// dist/index.js is generated by the build command (esbuild)
export { default } from "../dist/index.js";
